print(" ----- Calculating -----")
Num1 = int(input("Number 1 : "))
Num2 = int(input("Number 2 : "))
print(Num1, "+", Num2,"=",Num1 + Num2)
print(Num1, "-", Num2,"=",Num1 - Num2)
print(Num1, "*", Num2,"=",Num1 * Num2)
print(Num1, "/", Num2,"=",Num1 / Num2)